import "server-only";

/**
 * Where the answer's tokens come from.
 *
 * Ported from `geminiAnswerSource` / `openAIAnswerSource` /
 * `consumeServerSentEvents` in the iOS backend. Provider-agnostic on purpose:
 * the frame plumbing, the sentinel hold-back and the client-facing event
 * contract are identical whichever model produces the text, so switching
 * provider is a matter of swapping the delta source.
 *
 * Gemini is the intended provider, exactly as on iOS: the Animal Power profile
 * and System Dynamics content the answer is grounded in are both generated by
 * `gemini-2.5-flash`, so the assistant that explains them speaks from the same
 * model family. OpenAI is the fallback for when no Gemini key is configured, or
 * when Gemini rejects the request mid-flight.
 */

export const DEFAULT_GEMINI_ASK_MODEL = "gemini-2.5-flash";
export const DEFAULT_OPENAI_ASK_MODEL = "gpt-4o-mini";

/** Emits deltas until the model is done, or throws. */
export type AnswerDeltaSource = (emit: (delta: string) => void) => Promise<void>;

export type AskProviderName = "gemini" | "openai";

export function resolveGeminiAskModel(): string {
    return process.env.GEMINI_ANIMAL_POWER_MODEL?.trim()
        || process.env.GEMINI_PREMIUM_MODEL?.trim()
        || process.env.GEMINI_FAST_MODEL?.trim()
        || DEFAULT_GEMINI_ASK_MODEL;
}

export function resolveOpenAIAskModel(): string {
    return process.env.OPENAI_APPLIED_INSIGHT_MODEL?.trim()
        || process.env.OPENAI_PREMIUM_MODEL?.trim()
        || DEFAULT_OPENAI_ASK_MODEL;
}

export function geminiAskKey(): string | null {
    return process.env.GEMINI_API_KEY?.trim() || null;
}

export function openAIAskKey(): string | null {
    return process.env.OPENAI_API_KEY?.trim() || null;
}

/** Which providers this deployment can actually use, best first. */
export function availableAskProviders(): AskProviderName[] {
    const providers: AskProviderName[] = [];
    if (geminiAskKey()) providers.push("gemini");
    if (openAIAskKey()) providers.push("openai");
    return providers;
}

function extractGeminiText(frame: Record<string, unknown>): string {
    const candidates = Array.isArray(frame.candidates) ? frame.candidates : [];
    const candidate = candidates[0] as Record<string, unknown> | undefined;
    const content = candidate?.content as Record<string, unknown> | undefined;
    const parts = Array.isArray(content?.parts) ? content?.parts as unknown[] : [];
    return parts
        .map((part) => {
            const record = part as Record<string, unknown> | null;
            return typeof record?.text === "string" ? record.text : "";
        })
        .join("");
}

/** Reads an SSE body frame by frame, handing each `data:` payload to `onFrame`. */
export async function consumeServerSentEvents(
    body: ReadableStream<Uint8Array>,
    onFrame: (payload: Record<string, unknown>) => void,
    signal?: AbortSignal
): Promise<void> {
    const reader = body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";

    try {
        for (;;) {
            if (signal?.aborted) return;
            const {done, value} = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, {stream: true}).replace(/\r\n/g, "\n");

            // Frames are separated by a blank line; keep any partial tail.
            const frames = buffer.split("\n\n");
            buffer = frames.pop() ?? "";

            for (const frame of frames) {
                const line = frame.split("\n").find((candidate) => candidate.startsWith("data:"));
                if (!line) continue;
                const payload = line.slice(5).trim();
                if (!payload || payload === "[DONE]") continue;
                try {
                    onFrame(JSON.parse(payload) as Record<string, unknown>);
                } catch {
                    // A frame we cannot parse is skipped rather than failing the answer.
                }
            }
        }
    } finally {
        // A reader left open holds the socket for the life of the lambda.
        reader.releaseLock?.();
    }
}

type SourceParams = {
    systemPrompt: string;
    userPrompt: string;
    signal?: AbortSignal;
};

export function geminiAnswerSource(params: SourceParams & {key: string; model: string}): AnswerDeltaSource {
    return async (emit) => {
        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(params.model)}`
            + `:streamGenerateContent?alt=sse&key=${encodeURIComponent(params.key)}`,
            {
                method: "POST",
                headers: {"Content-Type": "application/json"},
                body: JSON.stringify({
                    systemInstruction: {parts: [{text: params.systemPrompt}]},
                    contents: [{role: "user", parts: [{text: params.userPrompt}]}],
                    generationConfig: {
                        temperature: 0.4,
                        // With thinkingBudget 0, maxOutputTokens is purely
                        // visible output. Left at the default, reasoning tokens
                        // eat the budget and the answer truncates mid-list.
                        maxOutputTokens: 2048,
                        thinkingConfig: {thinkingBudget: 0}
                    }
                }),
                signal: params.signal
            }
        );

        if (!response.ok || !response.body) {
            const detail = response.ok ? "empty_body" : (await response.text().catch(() => "")).slice(0, 300);
            throw new Error(`gemini_${response.status}: ${detail}`);
        }

        await consumeServerSentEvents(response.body, (frame) => {
            emit(extractGeminiText(frame));
        }, params.signal);
    };
}

export function openAIAnswerSource(params: SourceParams & {key: string; model: string}): AnswerDeltaSource {
    return async (emit) => {
        const response = await fetch("https://api.openai.com/v1/chat/completions", {
            method: "POST",
            headers: {
                Authorization: `Bearer ${params.key}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                model: params.model,
                temperature: 0.4,
                max_completion_tokens: 1600,
                stream: true,
                messages: [
                    {role: "system", content: params.systemPrompt},
                    {role: "user", content: params.userPrompt}
                ]
            }),
            signal: params.signal
        });

        if (!response.ok || !response.body) {
            const detail = response.ok ? "empty_body" : (await response.text().catch(() => "")).slice(0, 300);
            throw new Error(`openai_${response.status}: ${detail}`);
        }

        await consumeServerSentEvents(response.body, (frame) => {
            const choices = Array.isArray(frame.choices) ? frame.choices : [];
            const delta = (choices[0] as Record<string, unknown> | undefined)?.delta as
                Record<string, unknown> | undefined;
            if (typeof delta?.content === "string") emit(delta.content);
        }, params.signal);
    };
}

/** The delta source for one provider, or null when its key is missing. */
export function askAnswerSource(
    provider: AskProviderName,
    params: SourceParams
): AnswerDeltaSource | null {
    if (provider === "gemini") {
        const key = geminiAskKey();
        return key ? geminiAnswerSource({...params, key, model: resolveGeminiAskModel()}) : null;
    }
    const key = openAIAskKey();
    return key ? openAIAnswerSource({...params, key, model: resolveOpenAIAskModel()}) : null;
}

// MARK: - One-shot fallback

/**
 * The same answer in one piece, for when the stream could not be established.
 *
 * Streaming adds a second way for a turn to break — a dropped connection
 * part-way through, a proxy that buffers the body — and none of those are a
 * reason to lose an answer the model can still produce. iOS calls this path
 * `finishWithoutStreaming`.
 */
export async function requestAskAnswerJSON(params: {
    systemPrompt: string;
    userPrompt: string;
    signal?: AbortSignal;
}): Promise<{answer: string; followUps: string[]} | null> {
    const geminiKey = geminiAskKey();
    if (geminiKey) {
        const parsed = await requestGeminiJSON({...params, key: geminiKey, model: resolveGeminiAskModel()})
            .catch(() => null);
        if (parsed) return parsed;
    }

    const openaiKey = openAIAskKey();
    if (!openaiKey) return null;
    return await requestOpenAIJSON({...params, key: openaiKey, model: resolveOpenAIAskModel()})
        .catch(() => null);
}

function parseAnswerPayload(raw: string): {answer: string; followUps: string[]} | null {
    let parsed: unknown;
    try {
        parsed = JSON.parse(raw);
    } catch {
        return null;
    }
    if (!parsed || typeof parsed !== "object") return null;
    const record = parsed as Record<string, unknown>;
    const answer = typeof record.answer === "string"
        ? record.answer.trim()
        : typeof record.applied_insight === "string"
            ? record.applied_insight.trim()
            : "";
    if (!answer) return null;
    const rawFollowUps = record.follow_up_prompts ?? record.followUpPrompts;
    const followUps = Array.isArray(rawFollowUps)
        ? rawFollowUps
            .filter((item): item is string => typeof item === "string")
            .map((item) => item.trim())
            .filter((item) => item.length > 0 && item.length <= 120)
            .slice(0, 3)
        : [];
    return {answer, followUps};
}

async function requestGeminiJSON(params: {
    systemPrompt: string;
    userPrompt: string;
    key: string;
    model: string;
    signal?: AbortSignal;
}) {
    const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(params.model)}`
        + `:generateContent?key=${encodeURIComponent(params.key)}`,
        {
            method: "POST",
            headers: {"Content-Type": "application/json"},
            body: JSON.stringify({
                systemInstruction: {parts: [{text: params.systemPrompt}]},
                contents: [{role: "user", parts: [{text: params.userPrompt}]}],
                generationConfig: {
                    temperature: 0.35,
                    responseMimeType: "application/json",
                    maxOutputTokens: 2048,
                    thinkingConfig: {thinkingBudget: 0}
                }
            }),
            signal: params.signal
        }
    );
    if (!response.ok) throw new Error(`gemini_${response.status}`);
    const payload = await response.json() as Record<string, unknown>;
    return parseAnswerPayload(extractGeminiText(payload).trim());
}

async function requestOpenAIJSON(params: {
    systemPrompt: string;
    userPrompt: string;
    key: string;
    model: string;
    signal?: AbortSignal;
}) {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
            Authorization: `Bearer ${params.key}`,
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            model: params.model,
            temperature: 0.35,
            max_completion_tokens: 1600,
            response_format: {type: "json_object"},
            messages: [
                {role: "system", content: params.systemPrompt},
                {role: "user", content: params.userPrompt}
            ]
        }),
        signal: params.signal
    });
    if (!response.ok) throw new Error(`openai_${response.status}`);
    const payload = await response.json() as {choices?: Array<{message?: {content?: string}}>};
    const raw = payload.choices?.[0]?.message?.content;
    return raw ? parseAnswerPayload(raw) : null;
}
