insert into public.species_subtitles (locale, slug, descriptor, subtitle_story)
values
    ('en', 'white-backed-vulture', 'The pale-backed thermal scavenger animal', 'The White-backed Vulture is a broad-winged scavenger with a pale back, bare head, and efficient soaring flight over open country. It survives by finding carcasses early and turning distance into food access. For us, the message is simple: consistency can carry us through places where motivation alone cannot.'),
    ('en', 'hooded-vulture', 'The small scavenging cleanup bird animal', 'The Hooded Vulture is a smaller scavenger with a slim bill, bare face, and a strong tolerance for human-shaped landscapes. It stays effective by finding feeding opportunities other larger vultures may overlook. In human life, this reminds us that range and flexibility can open doors rigid strength cannot.'),
    ('en', 'water-monitor', 'The riverbank swimming monitor animal', 'The Water Monitor is a large lizard with a long neck, muscular tail, and strong swimming ability that lets it use riverbanks, mangroves, and urban edges. It succeeds by combining scavenging, hunting, and movement across both land and water. In human life, that means steady effort can outrun dramatic bursts that do not last.'),
    ('en', 'norwegian-forest-cat', 'The cold-forest longhair cat animal', 'The Norwegian Forest Cat is a large longhaired cat with a thick coat, strong frame, and climbing-focused build shaped by cold northern conditions. It stays effective by pairing insulation, balance, and patience in rough weather. Its lesson for us is clear: adapting well is often stronger than insisting on one fixed way.'),
    ('en', 'siberian-cat', 'The frost-built domestic forest cat animal', 'The Siberian Cat is a powerful longhaired cat with dense triple-layer fur, sturdy paws, and winter-ready movement. It is built to stay capable in cold environments where insulation and footing both matter. For us, the message is simple: progress comes faster when we lean into what works naturally and use it with intention.'),
    ('en', 'raven', 'The deep-voiced black trickster animal', 'The Raven is a large black corvid with a thick bill, wedge-shaped tail, and deep carrying voice. It survives by mixing intelligence, aerial control, and opportunistic feeding across harsh and variable landscapes. In human life, that means flexibility keeps us effective when the world changes around us.'),
    ('en', 'rook', 'The colony-field foraging corvid animal', 'The Rook is a social black corvid with a pale bare face at the bill base and a strong habit of feeding in open ground. It succeeds by turning flock behavior and repeated foraging routes into reliable access to food. Its lesson for us is clear: the right allies can multiply what one person can do alone.'),
    ('en', 'jackdaw', 'The pale-eyed cavity corvid animal', 'The Jackdaw is a small nimble corvid with pale eyes, quick flocking movement, and a habit of using cliffs, buildings, and cavities. It stays effective by being socially alert and structurally flexible in where it lives. In human life, this reminds us that range and flexibility can open doors rigid strength cannot.'),
    ('en', 'short-eared-owl', 'The open-country low-flight owl animal', 'The Short-eared Owl is a ground-nesting owl with long wings, open-country flight, and low coursing hunting behavior over grassland. It survives by turning wide visibility and patient listening into prey interception. In human life, this reminds us that not every win comes from moving first.'),
    ('en', 'masked-owl', 'The pale-faced silent night owl animal', 'The Masked Owl is a pale forest-edge owl with a large facial disc, strong low-light hearing, and quiet flight through dark cover. It remains effective by pairing silence with precise night-time sensing. For us, the message is simple: the better we read a situation, the less force we need later.'),
    ('en', 'asian-elephant', 'The memory-led trunk strategist animal', 'The Asian Elephant is a large herbivore with a dexterous trunk, smaller ears than African elephants, and deep memory for routes and resources. It survives by linking social knowledge, movement, and habitat familiarity across changing seasons. For us, the message is simple: strong communities make hard tasks lighter and safer.'),
    ('en', 'african-bush-elephant', 'The open-country landscape giant animal', 'The African Bush Elephant is a massive grazer-browser with broad ears, long movement range, and landscape-changing feeding behavior. It succeeds by turning size, memory, and group coordination into access across open country. Its lesson for us is clear: the right allies can multiply what one person can do alone.'),
    ('en', 'coyote', 'The edge-country adaptable hunter animal', 'The Coyote is a lean canid with keen hearing, adaptable diet, and the ability to live across wild, rural, and urban edges. It remains effective by adjusting behavior quickly instead of relying on one narrow habitat rule. In human life, this reminds us that range and flexibility can open doors rigid strength cannot.')
on conflict (locale, slug) do update
set descriptor = excluded.descriptor,
    subtitle_story = excluded.subtitle_story,
    updated_at = timezone('utc', now());
