insert into public.species_subtitles (locale, slug, descriptor, subtitle_story)
values
    ('en', 'bengal-tiger', 'The broad-framed striped ambush cat animal', 'The Bengal Tiger is a large striped cat with a heavy forequarter build, strong orange coat, and ambush-focused hunting style. It succeeds in forest and grassland mosaics by staying hidden until the last decisive movement matters. Its lesson for us is clear: timing matters just as much as effort.'),
    ('en', 'sumatran-tiger', 'The dense-forest striped stealth cat animal', 'The Sumatran Tiger is the smallest living tiger form, with dense striping, a compact build, and movement tuned for thick forest cover. It survives by turning tight vegetation and short-range surprise into hunting advantage. In human life, this reminds us that self-knowledge turns ability into direction.'),
    ('en', 'bornean-orangutan', 'The heavy-canopy memory ape animal', 'The Bornean Orangutan is a large reddish ape with powerful arms, deliberate canopy travel, and deep reliance on forest memory. It uses patience, route knowledge, and branch judgment to stay effective high above the ground. In human life, this reminds us that resilience is often built one repeatable step at a time.'),
    ('en', 'sumatran-orangutan', 'The high-canopy route-planning ape animal', 'The Sumatran Orangutan is a slimmer forest ape with long arms, refined canopy movement, and strong dependence on complex treetop routes. It survives by pairing careful planning with the ability to move through layered forest without wasting energy. In human life, this reminds us that resilience is often built one repeatable step at a time.'),
    ('en', 'tapanuli-orangutan', 'The rare ridge-forest orangutan animal', 'The Tapanuli Orangutan is a rare orangutan from the Batang Toru ecosystem with shaggy hair, isolated range, and specialized forest adaptation. Its survival depends on maintaining continuity across a fragile mountain forest system. In human life, that means flexibility keeps us effective when the world changes around us.'),
    ('en', 'sea-turtle', 'The long-route ocean grazer animal', 'The Sea Turtle is a marine reptile with flipper-shaped limbs, a streamlined shell, and long-distance ocean navigation ability. It turns currents, coastlines, and feeding grounds into one connected migration system. For us, the message is simple: people who can adjust without losing themselves stay hard to stop.')
on conflict (locale, slug) do update
set descriptor = excluded.descriptor,
    subtitle_story = excluded.subtitle_story,
    updated_at = timezone('utc', now());
