insert into public.species_subtitles (locale, slug, descriptor, subtitle_story)
values
    ('en', 'pika', 'The alpine stone-cache squeaker animal', 'The Pika is a small mountain mammal with rounded ears and a compact body that lives among cool broken rocks. It gathers mouthfuls of plants into haypiles before winter, showing how preparation matters when the hard season is coming. In human life, this reminds us that healing and patience can be productive forms of strength.'),
    ('en', 'snake', 'The limbless scent-tracking survivor animal', 'The Snake is a limbless reptile that uses its tongue to read scent in the air and its scales to move through grass, soil, and water. It survives in many different habitats because its whole body is built for efficient motion without wasted parts. In human life, that means flexibility keeps us effective when the world changes around us.'),
    ('en', 'carp', 'The bottom-feeding freshwater forager animal', 'The Carp is a sturdy freshwater fish that searches the bottom with a barbel-fringed mouth for edible bits in mud and weeds. It turns ponds and slow rivers into reliable feeding ground by staying patient and close to the substrate. In human life, that means waiting for the right moment can beat forcing the wrong one.'),
    ('en', 'owl', 'The silent night-listening hunter animal', 'The Owl is a bird with forward-facing eyes, soft flight feathers, and hearing tuned for the dark. It can locate small movement at night by listening carefully and flying with almost no sound. In human life, that means paying close attention can reveal options other people miss.'),
    ('en', 'domestic-chicken', 'The ground-scratching flock signaler animal', 'The Chicken is a familiar ground bird that scratches for seeds and insects with its feet while staying close to the flock. It does best when quick signals, shared awareness, and simple routines keep the group moving together. For us, the message is simple: strong communities make hard tasks lighter and safer.'),
    ('en', 'shark', 'The sensing open-water predator animal', 'The Shark is a fish built with a flexible cartilaginous frame, exposed gill slits, and teeth that are replaced again and again. Its design stays effective because nearly every part of the body is tuned for sensing, swimming, and biting in moving water. Its lesson for us is clear: adapting well is often stronger than insisting on one fixed way.'),
    ('en', 'seal', 'The blubber-built coastal diver animal', 'The Seal is a marine mammal with a streamlined body, thick blubber, and strong flippers for cold-water swimming. It moves easily between shore and sea because insulation, shape, and propulsion all work as one system. Its lesson for us is clear: adapting well is often stronger than insisting on one fixed way.'),
    ('en', 'penguin', 'The cold-current torpedo bird animal', 'The Penguin is a seabird that stands upright on land but turns into a fast underwater hunter once it enters the sea. Its flipper-like wings and dense waterproof feathers make cold water a place it can use instead of fear. In human life, that means our best results often come from understanding what we are built for and using it well.'),
    ('en', 'otter', 'The playful river-rolling hunter animal', 'The Otter is a sleek waterside mammal with dense fur and a flexible body that helps it twist, dive, and chase through rivers and wetlands. It looks playful, but that movement is also a precise way of hunting in a fast-changing edge habitat. In human life, that means flexibility keeps us effective when the world changes around us.'),
    ('en', 'deer', 'The alert edge-grazing runner animal', 'The Deer is a long-legged grazer with alert ears and quick reactions that help it read open edges before danger gets too close. It survives by noticing change early and turning speed into distance at the right moment. For us, the message is simple: patience turns preparation into real advantage.'),
    ('en', 'robin', 'The red-breasted garden song scout animal', 'The Robin is a compact songbird that watches the ground closely before hopping in to grab worms, insects, and other small food. It makes ordinary gardens and woodland edges useful by staying observant and moving with quick precision. For us, the message is simple: the better we read a situation, the less force we need later.'),
    ('en', 'finch', 'The seed-cracking flock songbird animal', 'The Finch is a small bird with a short conical bill made for cracking seeds that many other animals leave behind. It succeeds by matching a specialized tool to a common resource and using it again and again. In human life, that means mastering one real strength can matter more than trying to do everything.'),
    ('en', 'lizard', 'The sun-warmed quick-dart reptile animal', 'The Lizard is a scaled reptile that depends on warmth, quick stop-start movement, and sharp timing to stay effective. It uses heat, cover, and sudden bursts of motion to make a small body feel much harder to catch. For us, the message is simple: patience turns preparation into real advantage.'),
    ('en', 'crab', 'The hard-shelled sideways walker animal', 'The Crab is a hard-shelled animal with a sideways body plan and strong front claws for feeding and defense. Its shape looks unusual, but every part helps it move through tight shorelines, muddy banks, and reef cracks with control. In human life, that means flexibility keeps us effective when the world changes around us.'),
    ('en', 'fox', 'The quiet edge-country opportunist animal', 'The Fox is a narrow-faced hunter with a bushy tail and flexible habits that let it live at the edge of wild and human spaces. It stays successful by adjusting its tactics to whatever food, cover, and opportunity the landscape offers. In human life, this reminds us that range and flexibility can open doors rigid strength cannot.'),
    ('en', 'cormorant', 'The hooked-bill fish-diving hunter animal', 'The Cormorant is a dark waterbird with a hooked bill and a low-riding posture that helps it dive after fish. It turns coastline, lakes, and estuaries into hunting lanes by pursuing prey underwater instead of waiting above it. Its lesson for us is clear: timing matters just as much as effort.'),
    ('en', 'cat', 'The soft-footed ambush pouncer animal', 'The Cat is a soft-footed predator with retractable claws, forward-facing eyes, and a body made for stalking and pouncing. It shows how patience, quiet movement, and short explosive action can work better than constant effort. For us, the message is simple: the better we read a situation, the less force we need later.'),
    ('en', 'grasshopper', 'The spring-legged grassland jumper animal', 'The Grasshopper is an insect with powerful hind legs and body colors that blend into stems, leaves, and dry ground. It survives by staying hard to notice until one sudden jump creates the space it needs. For us, the message is simple: people who can adjust without losing themselves stay hard to stop.')
on conflict (locale, slug) do update
set descriptor = excluded.descriptor,
    subtitle_story = excluded.subtitle_story,
    updated_at = timezone('utc', now());
