create table if not exists public.admin_social_metric_snapshots (
    id bigint generated by default as identity primary key,
    platform text not null,
    followers bigint,
    views bigint,
    posts bigint,
    raw_metrics jsonb not null default '{}'::jsonb,
    recorded_at timestamptz not null default now()
);

create index if not exists admin_social_metric_snapshots_platform_recorded_idx
    on public.admin_social_metric_snapshots (platform, recorded_at desc);

alter table public.admin_social_metric_snapshots enable row level security;
